Angular2/Angular2/Controllers/RolesAdminController.cs
using Angular2.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;

namespace Angular2.Controllers
{
    // [Authorize(Roles = "Admin")]
    public class RolesAdminController : Controller
    {
        public RolesAdminController()
        {
        }

        public RolesAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

	//
	// GET: /Roles/
        //public ActionResult Index()
        //{
        //    return View(RoleManager.Roles);
        //}

        [HttpGet]
        public JsonResult GetRoles()
        {
            return Json(new
            {
                roles = RoleManager.Roles.Select(p => new
                {
                    p.Name,
                    p.Id,
                    p.Description
                }).ToList()
            }, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Roles/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //
        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            // Initialize ApplicationRole instead of IdentityRole:
            var status = false;
            var message = string.Empty;

            try
            {
                var role = new ApplicationRole(roleViewModel.Name);
                role.Description = roleViewModel.Description;

                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    message = roleresult.Errors.First();
                }
                else
                {
                    status = true;
                    message = "Role record added successfully.";
                }
            }
            catch (System.Exception ex)
            {
                message = "Error while trying to create role. Error: " + ex.Message;
            }
            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }
        
        //
        // GET: /Roles/Edit/Admin
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel
            {
                Id = role.Id,
                Name = role.Name,
                Description = role.Description
            };
            return View(roleModel);
        }

        //
	// POST: /Roles/Edit/5
	[HttpPut]

	public async Task<ActionResult> Edit(RoleViewModel roleModel)
	{
            var status = false;
            var message = string.Empty;

            try
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                // Update the new Description property:
                role.Description = roleModel.Description;

                await RoleManager.UpdateAsync(role);
                status = true;
                message = "Role record updated successfully.";
            }
            catch (System.Exception ex)
            {
                message = "Error while trying to update role. Error: " + ex.Message;
            }
            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Roles/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        //
        // POST: /Roles/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            	var status = false;
		var message = string.Empty;

		var role = await RoleManager.FindByIdAsync(id);

		if (role == null)
		{
		    message = "Role does not exist.";
		}
		else
		{
                if (UserManager.Users.Any(u => u.Roles.Any(r => r.RoleId == id)))
                {
                    message = "Selected role is currently in use. Please remove this role from all users before removing the role..";
                }
                else
                {
		    IdentityResult result;
		    result = await RoleManager.DeleteAsync(role);
		    if (!result.Succeeded)
		    {
			message = result.Errors.First();
		    }
		    else
		    {
			message = "Role has been successfully deleted.";
			status = true;
		    }
		}
            }
            return Json(new { status = status, message =message}, JsonRequestBehavior.AllowGet);
        }
    }
}

Angular2/Angular2/Views/RolesAdmin/Create.cshtml
@model Angular2.Models.RoleViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Role</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel panel-default">
        <div class="panel-heading">
            Create Role
        </div>
        <div class="panel-body">
    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>
    </div>
        </div>
        <div class="panel-footer clearfix">
            <div class="pull-right">
			<button type="submit" value="Create Role" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Save</button>
			&nbsp;
			@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Angular2/Angular2/Views/RolesAdmin/Delete.cshtml
@model Angular2.Models.ApplicationRole

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Role</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        Delete Role
    </div>
    <div class="panel-body">
        <h4>Are you sure you want to delete this Role? </h4>
        <p>Deleting this Role will remove all users from this role. It will not delete the users.</p>
        <div>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
        </div>
    </div>
    <div class="panel-footer clearfix">
        <div class="pull-right">
            @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <button type="submit" value="Delete Role" class="btn btn-primary"><span class="glyphicon glyphicon-remove"></span> Delete</button>
                    &nbsp;
                    @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-primary"})
                </div>
            }
        </div>
    </div>
</div>

Angular2/Angular2/Views/RolesAdmin/Details.cshtml
@model Angular2.Models.ApplicationRole

@{
    ViewBag.Title = "Details";
}

<h2>Role Details</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        Role Details
    </div>
    <div class="panel-body">
        <div>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
        </div>
        <h4>List of users in this role</h4>
        @if (ViewBag.UserCount == 0)
        {
            <hr />
            <p>No users found in this role.</p>
        }

        <table class="table">

            @foreach (var item in ViewBag.Users)
            {
                <tr>
                    <td>
                        @item.UserName
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer clearfix">
        <div class="pull-right">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <a href="@Url.Action("Edit", new {@id = Model.Id})" value="Edit Role" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                    &nbsp;
                    @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-primary"})
                </div>
            }
        </div>
    </div>
</div>

Angular2/Angular2/Views/RolesAdmin/Edit.cshtml
@model Angular2.Models.RoleViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Role</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="panel panel-default">
        <div class="panel-heading">
            Edit Role
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer clearfix">
            <div class="pull-right">
			<button type="submit" value="Edit Role" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Save</button>
			&nbsp;
			@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Angular2/Angular2/Views/RolesAdmin/Index.cshtml
@model IEnumerable<Angular2.Models.ApplicationRole>

@{
    ViewBag.Title = "Index";
}

<h2>Roles List</h2>

<p class="pull-right">
    <a href="@Url.Action("Create", "RolesAdmin")" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Create New</a>
</p>
<table class="table table-bordered table-condensed table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
		Actions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>