mvc/NewWebsite/NewWebsite/Controllers/sa106aController.cs
#region History
/************************CREATION HISTORY*********************************
 * Created By		: CodeBhagat v1.0
 * Created Date		: 2017/1/13
 * Purpose			: This is an MVC Controller class that calls methods to perform 
 *					  Data Layer operations and returns to View
 * *********************UPDATION HISTORY******************************
 * 
 * Updated By		Updated Date			Comments
 * ------------------------------------------------------------
*/
#endregion

#region Using Statements	
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Linq;
//using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
//using jqMvcGrid.Models;
using OfficeOpenXml;		// Namespace from EP Plus component
using OfficeOpenXml.Style;	// Namespace from EP Plus component
using NewWebsite.Models;
using NewWebsite.Helper;
#endregion

namespace NewWebsite
{
	[Authorize]
	[OutputCache(NoStore = true, Duration = 0)]
    public class sa106aController : Controller
    {
        //private Isa106aRepository _repository = new sa106aRepository();

        //
        // GET: /sa106a/
        public ActionResult Index()
        {
			PopulateLookups();
            return View(new sa106aData());
        }

        public ActionResult GetList(int pageIndex, int pageSize, string sortExpression)
        {
            int rowsCount = 0;
            string filterExpression = GetFilterExpression();
			if (string.IsNullOrEmpty(sortExpression))
				sortExpression = "gkey asc";
            List<sa106aData> objsa106aList = NewWebsite.Models.sa106a.GetList(filterExpression, sortExpression, pageIndex, pageSize, out rowsCount).ToList();
			var model = from objsa106a in objsa106aList.AsQueryable()
						select new
						{
						gkey = objsa106a.gkey,
						serialno = objsa106a.serialno,
						sa106gkey = objsa106a.sa106gkey,
						ba101gkey = objsa106a.ba101gkey,
						ba110gkey = objsa106a.ba110gkey,
						ba113gkey = objsa106a.ba113gkey,
						mr200gkey = objsa106a.mr200gkey,
						mr200agkey = objsa106a.mr200agkey,
						ba120gkey = objsa106a.ba120gkey,
						ba121gkey = objsa106a.ba121gkey,
						ba106gkey = objsa106a.ba106gkey,
						shipmentdate = objsa106a.shipmentdate,
						canceldate = objsa106a.canceldate,
						cancelreason = objsa106a.cancelreason,
						activityid = objsa106a.activityid,
						activityname = objsa106a.activityname,
						quantity = objsa106a.quantity,
						nodisprice = objsa106a.nodisprice,
						noamount = objsa106a.noamount,
						disprice = objsa106a.disprice,
						cancelqty = objsa106a.cancelqty,
						cancelamt = objsa106a.cancelamt,
						outquantity = objsa106a.outquantity,
						retquantity = objsa106a.retquantity,
						prepono = objsa106a.prepono,
						mr210gkey = objsa106a.mr210gkey,
						mr210agkey = objsa106a.mr210agkey,
						remark = objsa106a.remark,
						replication_create = objsa106a.replication_create,
						replication_update = objsa106a.replication_update,
						inventoryQty = objsa106a.inventoryQty,
						outstockQty = objsa106a.outstockQty,
						tstdqty = objsa106a.tstdqty,
						ba126gkey = objsa106a.ba126gkey,
						webgkey = objsa106a.webgkey,
						canadaamt = objsa106a.canadaamt,
						ba117gkey = objsa106a.ba117gkey,

						};
			var objGridData = new
            {
                data = from record in model
					   select record,
				pageSize = rowsCount
            };

			var result = Json(objGridData, JsonRequestBehavior.AllowGet);
	        result.MaxJsonLength = int.MaxValue;
			return result;
        }
		
        public ActionResult List(int page, int rows, string search, string sidx, string sord)
        {
            int rowsCount = 0;
			string filterExpression = (search != null ? "gkey like '%" + search + "%'" : string.Empty);
            List<sa106aData> objsa106aList = NewWebsite.Models.sa106a.GetList(filterExpression, sidx + " " + sord, page, rows, out rowsCount);

            var model = from objsa106a in objsa106aList.AsQueryable()
                        select new
                        {
                            Edit = "<a style='color:#5c87b2' href='" + "sa106a/Edit/" + objsa106a.gkey + "'>Edit</a>",
                            Details = "<a style='color:#5c87b2' href='" + "sa106a/Details/" + objsa106a.gkey + "'>Details</a>",
                            						gkey = objsa106a.gkey,
						serialno = objsa106a.serialno,
						sa106gkey = objsa106a.sa106gkey,
						ba101gkey = objsa106a.ba101gkey,
						ba110gkey = objsa106a.ba110gkey,
						ba113gkey = objsa106a.ba113gkey,
						mr200gkey = objsa106a.mr200gkey,
						mr200agkey = objsa106a.mr200agkey,
						ba120gkey = objsa106a.ba120gkey,
						ba121gkey = objsa106a.ba121gkey,
						ba106gkey = objsa106a.ba106gkey,
						shipmentdate = objsa106a.shipmentdate,
						canceldate = objsa106a.canceldate,
						cancelreason = objsa106a.cancelreason,
						activityid = objsa106a.activityid,
						activityname = objsa106a.activityname,
						quantity = objsa106a.quantity,
						nodisprice = objsa106a.nodisprice,
						noamount = objsa106a.noamount,
						disprice = objsa106a.disprice,
						cancelqty = objsa106a.cancelqty,
						cancelamt = objsa106a.cancelamt,
						outquantity = objsa106a.outquantity,
						retquantity = objsa106a.retquantity,
						prepono = objsa106a.prepono,
						mr210gkey = objsa106a.mr210gkey,
						mr210agkey = objsa106a.mr210agkey,
						remark = objsa106a.remark,
						replication_create = objsa106a.replication_create,
						replication_update = objsa106a.replication_update,
						inventoryQty = objsa106a.inventoryQty,
						outstockQty = objsa106a.outstockQty,
						tstdqty = objsa106a.tstdqty,
						ba126gkey = objsa106a.ba126gkey,
						webgkey = objsa106a.webgkey,
						canadaamt = objsa106a.canadaamt,
						ba117gkey = objsa106a.ba117gkey,

                        };
			var objGridData = new 
            {
                Page = page,
                Records = rowsCount,
                Rows = from record in model
                       select record,
                Total = ((int) (rowsCount/rows)) + 1,
            };

            var result = Json(objGridData, JsonRequestBehavior.AllowGet);
	        result.MaxJsonLength = int.MaxValue;
			return result;


			// Enable below code if you are using Entity Framework
			/*
            var repository = new sa106aRepository();
            var model = from objsa106a in repository.Index().OrderBy(sidx + " " + sord)
                        select new
                        {
                            Edit = "<a style='color:#5c87b2' href='" + "sa106a/Edit/" + objsa106a.gkey + "'>Edit</a>",
                            Details = "<a style='color:#5c87b2' href='" + "sa106a/Details/" + objsa106a.gkey + "'>Details</a>",
                            						gkey = objsa106a.gkey,
						serialno = objsa106a.serialno,
						sa106gkey = objsa106a.sa106gkey,
						ba101gkey = objsa106a.ba101gkey,
						ba110gkey = objsa106a.ba110gkey,
						ba113gkey = objsa106a.ba113gkey,
						mr200gkey = objsa106a.mr200gkey,
						mr200agkey = objsa106a.mr200agkey,
						ba120gkey = objsa106a.ba120gkey,
						ba121gkey = objsa106a.ba121gkey,
						ba106gkey = objsa106a.ba106gkey,
						shipmentdate = objsa106a.shipmentdate,
						canceldate = objsa106a.canceldate,
						cancelreason = objsa106a.cancelreason,
						activityid = objsa106a.activityid,
						activityname = objsa106a.activityname,
						quantity = objsa106a.quantity,
						nodisprice = objsa106a.nodisprice,
						noamount = objsa106a.noamount,
						disprice = objsa106a.disprice,
						cancelqty = objsa106a.cancelqty,
						cancelamt = objsa106a.cancelamt,
						outquantity = objsa106a.outquantity,
						retquantity = objsa106a.retquantity,
						prepono = objsa106a.prepono,
						mr210gkey = objsa106a.mr210gkey,
						mr210agkey = objsa106a.mr210agkey,
						remark = objsa106a.remark,
						replication_create = objsa106a.replication_create,
						replication_update = objsa106a.replication_update,
						inventoryQty = objsa106a.inventoryQty,
						outstockQty = objsa106a.outstockQty,
						tstdqty = objsa106a.tstdqty,
						ba126gkey = objsa106a.ba126gkey,
						webgkey = objsa106a.webgkey,
						canadaamt = objsa106a.canadaamt,
						ba117gkey = objsa106a.ba117gkey,

                            //CategoryName = "<a href=''>" + objsa106a.CategoryName + "</a>",
                        };
            return Json(model.ToJqGridData(page, rows, null, search,
                new[] { "CategoryName", "Description" }));
			*/
        }

		public void PopulateLookups()
		{
			
		}

        //
        // GET: /sa106a/Details/5
        public ActionResult Details(string id)
        {
			ViewBag.ErrorMsg = Session["ErrorMsg"];
            return View(NewWebsite.Models.sa106a.GetDetailsByID(id));
        }

        //
        // GET: /sa106a/Create
        public ActionResult Create()
        {
			PopulateLookups();
            return View(new NewWebsite.Models.sa106aData());
        }

        //
        // POST: /sa106a/Create
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(sa106aData objsa106aData, FormCollection collection)
        {
            try
            {
                // Validate
                //if (!Validate(objsa106aData))
                //    return View();
				
				if (ModelState.IsValid)
				{
	                // Create
	                if (NewWebsite.Models.sa106a.Add(objsa106aData) != string.Empty)
					{
						this.ShowMessage(MessageType.Success, "The record was saved successfully!!!", true);
		                return RedirectToAction("Index");
					}
				}
            }
            catch(Exception ex)
            {
				Session["ErrorMsg"] = "Error: Please try again!!!<br />" + ex.Message;
				ViewBag.ErrorMsg = Session["ErrorMsg"];
            }
			PopulateLookups();
			return View(objsa106aData);
        }

        //
        // GET: /sa106a/Edit/5

mvc/NewWebsite/NewWebsite/Views/sa106a/Create.cshtml
@model NewWebsite.Models.sa106aData

@{
    ViewBag.Title = "Create sa106a";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Create Sa106a</h3>
    @using (Html.BeginForm()) {
		{
        <fieldset>
            <div class="row">
                    &nbsp;
            </div>
            <div class="panel panel-default">
				<div class="panel-heading"><b>Add Sa106a</b></div>
                <div class="panel-body">
					<table>
					
			<tr>
                <td><label for="gkey">Gkey:</label></td>
				<td>@Html.TextBox("gkey", Model.gkey, new { @id="lblgkey", @class = "form-control", @readonly = "readonly"}) </td>
            </tr>
			<tr>
                <td><label for="serialno">Serialno:</label></td>
				<td>@Html.TextBox("serialno", Model.serialno, new { @id="txtserialno", @class = "form-control"}) @Html.ValidationMessage("serialno", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="sa106gkey">Sa106gkey:</label></td>
				<td>@Html.TextBox("sa106gkey", Model.sa106gkey, new { @id="txtsa106gkey", @class = "form-control"}) @Html.ValidationMessage("sa106gkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="ba101gkey">Ba101gkey:</label></td>
				<td>@Html.TextBox("ba101gkey", Model.ba101gkey, new { @id="txtba101gkey", @class = "form-control"}) @Html.ValidationMessage("ba101gkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="ba110gkey">Ba110gkey:</label></td>
				<td>@Html.TextBox("ba110gkey", Model.ba110gkey, new { @id="txtba110gkey", @class = "form-control"}) @Html.ValidationMessage("ba110gkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="ba113gkey">Ba113gkey:</label></td>
				<td>@Html.TextBox("ba113gkey", Model.ba113gkey, new { @id="txtba113gkey", @class = "form-control"}) @Html.ValidationMessage("ba113gkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="mr200gkey">Mr200gkey:</label></td>
				<td>@Html.TextBox("mr200gkey", Model.mr200gkey, new { @id="txtmr200gkey", @class = "form-control"}) @Html.ValidationMessage("mr200gkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="mr200agkey">Mr200agkey:</label></td>
				<td>@Html.TextBox("mr200agkey", Model.mr200agkey, new { @id="txtmr200agkey", @class = "form-control"}) @Html.ValidationMessage("mr200agkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="ba120gkey">Ba120gkey:</label></td>
				<td>@Html.TextBox("ba120gkey", Model.ba120gkey, new { @id="txtba120gkey", @class = "form-control"}) @Html.ValidationMessage("ba120gkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="ba121gkey">Ba121gkey:</label></td>
				<td>@Html.TextBox("ba121gkey", Model.ba121gkey, new { @id="txtba121gkey", @class = "form-control"}) @Html.ValidationMessage("ba121gkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="ba106gkey">Ba106gkey:</label></td>
				<td>@Html.TextBox("ba106gkey", Model.ba106gkey, new { @id="txtba106gkey", @class = "form-control"}) @Html.ValidationMessage("ba106gkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="shipmentdate">Shipment Date:</label></td>
				<td>@Html.TextBox("shipmentdate", Model.shipmentdate, new { @id="txtshipmentdate", @class = "form-control"}) @Html.ValidationMessage("shipmentdate", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="canceldate">Cancel Date:</label></td>
				<td>@Html.TextBox("canceldate", Model.canceldate, new { @id="txtcanceldate", @class = "form-control"}) @Html.ValidationMessage("canceldate", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="cancelreason">Cancelreason:</label></td>
				<td>@Html.TextArea("cancelreason", Model.cancelreason.ToString(), new { @id="txtcancelreason", @class = "form-control", @rows=5, @cols=40})@Html.ValidationMessage("cancelreason", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="activityid">Activity Id:</label></td>
				<td>@Html.TextArea("activityid", Model.activityid.ToString(), new { @id="txtactivityid", @class = "form-control", @rows=5, @cols=40})@Html.ValidationMessage("activityid", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="activityname">Activity Name:</label></td>
				<td>@Html.TextArea("activityname", Model.activityname.ToString(), new { @id="txtactivityname", @class = "form-control", @rows=5, @cols=40})@Html.ValidationMessage("activityname", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="quantity">Quantity:</label></td>
				<td>@Html.TextBox("quantity", Model.quantity, new { @id="txtquantity", @class = "form-control"}) @Html.ValidationMessage("quantity", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="nodisprice">Nodisprice:</label></td>
				<td>@Html.TextBox("nodisprice", Model.nodisprice, new { @id="txtnodisprice", @class = "form-control"}) @Html.ValidationMessage("nodisprice", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="noamount">Noamount:</label></td>
				<td>@Html.TextBox("noamount", Model.noamount, new { @id="txtnoamount", @class = "form-control"}) @Html.ValidationMessage("noamount", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="disprice">Disprice:</label></td>
				<td>@Html.TextBox("disprice", Model.disprice, new { @id="txtdisprice", @class = "form-control"}) @Html.ValidationMessage("disprice", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="cancelqty">Cancelqty:</label></td>
				<td>@Html.TextBox("cancelqty", Model.cancelqty, new { @id="txtcancelqty", @class = "form-control"}) @Html.ValidationMessage("cancelqty", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="cancelamt">Cancelamt:</label></td>
				<td>@Html.TextBox("cancelamt", Model.cancelamt, new { @id="txtcancelamt", @class = "form-control"}) @Html.ValidationMessage("cancelamt", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="outquantity">Outquantity:</label></td>
				<td>@Html.TextBox("outquantity", Model.outquantity, new { @id="txtoutquantity", @class = "form-control"}) @Html.ValidationMessage("outquantity", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="retquantity">Retquantity:</label></td>
				<td>@Html.TextBox("retquantity", Model.retquantity, new { @id="txtretquantity", @class = "form-control"}) @Html.ValidationMessage("retquantity", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="prepono">Prepono:</label></td>
				<td>@Html.TextBox("prepono", Model.prepono, new { @id="txtprepono", @class = "form-control"}) @Html.ValidationMessage("prepono", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="mr210gkey">Mr210gkey:</label></td>
				<td>@Html.TextBox("mr210gkey", Model.mr210gkey, new { @id="txtmr210gkey", @class = "form-control"}) @Html.ValidationMessage("mr210gkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="mr210agkey">Mr210agkey:</label></td>
				<td>@Html.TextBox("mr210agkey", Model.mr210agkey, new { @id="txtmr210agkey", @class = "form-control"}) @Html.ValidationMessage("mr210agkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="remark">Remark:</label></td>
				<td>@Html.TextArea("remark", Model.remark.ToString(), new { @id="txtremark", @class = "form-control", @rows=5, @cols=40})@Html.ValidationMessage("remark", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="replication_create">Replication Create:</label></td>
				<td>@Html.TextBox("replication_create", Model.replication_create, new { @id="txtreplication_create", @class = "form-control"}) @Html.ValidationMessage("replication_create", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="replication_update">Replication Up Date:</label></td>
				<td>@Html.TextBox("replication_update", Model.replication_update, new { @id="txtreplication_update", @class = "form-control"}) @Html.ValidationMessage("replication_update", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="inventoryQty">Inventoryqty:</label></td>
				<td>@Html.TextBox("inventoryQty", Model.inventoryQty, new { @id="txtinventoryQty", @class = "form-control"}) @Html.ValidationMessage("inventoryQty", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="outstockQty">Outstockqty:</label></td>
				<td>@Html.TextBox("outstockQty", Model.outstockQty, new { @id="txtoutstockQty", @class = "form-control"}) @Html.ValidationMessage("outstockQty", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="tstdqty">Tstdqty:</label></td>
				<td>@Html.TextBox("tstdqty", Model.tstdqty, new { @id="txttstdqty", @class = "form-control"}) @Html.ValidationMessage("tstdqty", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="ba126gkey">Ba126gkey:</label></td>
				<td>@Html.TextBox("ba126gkey", Model.ba126gkey, new { @id="txtba126gkey", @class = "form-control"}) @Html.ValidationMessage("ba126gkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="webgkey">Webgkey:</label></td>
				<td>@Html.TextBox("webgkey", Model.webgkey, new { @id="txtwebgkey", @class = "form-control"}) @Html.ValidationMessage("webgkey", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="canadaamt">Canadaamt:</label></td>
				<td>
						<div class="input-group">
							<div class="input-group-addon">$</div>
							@Html.TextBox("canadaamt", Model.canadaamt, new { @id="txtcanadaamt", @class = "form-control text-right", @style="width:150px;" }) 
						</div>
					@Html.ValidationMessage("canadaamt", "", new { @class = "text-danger" }) </td>
            </tr>
			<tr>
                <td><label for="ba117gkey">Ba117gkey:</label></td>
				<td>@Html.TextBox("ba117gkey", Model.ba117gkey, new { @id="txtba117gkey", @class = "form-control"}) @Html.ValidationMessage("ba117gkey", "", new { @class = "text-danger" }) </td>
            </tr>
					</table>
				</div>
		        <div class="panel-footer">
					<div class="row">
						<div class="pull-right">
							<button type="submit" value="Create" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Save</button>
							&nbsp;
							<a href="@Url.Action("Index", "sa106a")" class="btn btn-primary"><span class="glyphicon glyphicon-arrow-left"></span> Back to List</a>
						</div>
					</div>
				</div>
			</div>
        </fieldset>
		}
    }